cursor --install-extension astro-build.astro-vscode
cursor --install-extension bradlc.vscode-tailwindcss
cursor --install-extension charliermarsh.ruff
cursor --install-extension davidanson.vscode-markdownlint
cursor --install-extension dbaeumer.vscode-eslint
cursor --install-extension eamodio.gitlens
cursor --install-extension editorconfig.editorconfig
cursor --install-extension esbenp.prettier-vscode
cursor --install-extension github.vscode-pull-request-github
cursor --install-extension golang.go
cursor --install-extension ms-azuretools.vscode-docker
cursor --install-extension ms-python.debugpy
cursor --install-extension ms-python.python
cursor --install-extension ms-python.vscode-pylance
cursor --install-extension ms-toolsai.jupyter
cursor --install-extension ms-toolsai.jupyter-renderers
cursor --install-extension ms-toolsai.vscode-jupyter-cell-tags
cursor --install-extension ms-toolsai.vscode-jupyter-slideshow
cursor --install-extension stripe.markdoc-language-support
cursor --install-extension unifiedjs.vscode-mdx
cursor --install-extension vscode-icons-team.vscode-icons
cursor --install-extension yoavbls.pretty-ts-errors
